field: 31a22723-b618-4563-88b9-f635e59c6bcc
fieldLayouts:
  00675269-91f2-438d-8b9b-5ea1696d0dab:
    tabs:
      -
        elements:
          -
            fieldUid: 8090eb7b-aaff-4a2c-815a-bf3e451d9d65
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 99258b34-ea51-4f50-a596-097fe70ceea9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  8090eb7b-aaff-4a2c-815a-bf3e451d9d65:
    contentColumnType: text
    fieldGroup: null
    handle: titleTopOffers
    instructions: ''
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  99258b34-ea51-4f50-a596-097fe70ceea9:
    contentColumnType: string
    fieldGroup: null
    handle: card
    instructions: ''
    name: Card
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '3'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources:
        - 'section:5f6e6227-0d66-4c11-b99c-68f24376a454'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: topoffers
name: 'Top offers'
sortOrder: 5
