contentColumnType: string
fieldGroup: 82828b93-6caf-4494-b888-29874f6867db
handle: emailClient
instructions: ''
name: Email
searchable: false
settings:
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
