contentColumnType: string
fieldGroup: 82828b93-6caf-4494-b888-29874f6867db
handle: image
instructions: ''
name: Image
searchable: false
settings:
  allowSelfRelations: false
  allowedKinds: null
  defaultUploadLocationSource: 'volume:7cb34f59-d1f7-4250-ac34-c1698263af23'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:7cb34f59-d1f7-4250-ac34-c1698263af23'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:7cb34f59-d1f7-4250-ac34-c1698263af23'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
