contentColumnType: text
fieldGroup: 82828b93-6caf-4494-b888-29874f6867db
handle: messageClient
instructions: ''
name: 'Your message'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
