contentColumnType: integer(10)
fieldGroup: 82828b93-6caf-4494-b888-29874f6867db
handle: numberOfBeds
instructions: ''
name: 'Number of beds'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: '0'
  prefix: ''
  previewCurrency: ''
  previewFormat: decimal
  size: null
  suffix: beds
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
