contentColumnType: 'decimal(12,2)'
fieldGroup: 82828b93-6caf-4494-b888-29874f6867db
handle: price
instructions: ''
name: Price
searchable: false
settings:
  decimals: '2'
  defaultValue: null
  max: null
  min: '0'
  prefix: ''
  previewCurrency: USD
  previewFormat: currency
  size: null
  suffix: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
