contentColumnType: text
fieldGroup: 29f996c1-1c5b-468e-b06f-13c41110227b
handle: socialNetworkIcon
instructions: 'Choose an icon on the Font Awesome website (https://fontawesome.com/) and copy the class name of the chosen icon.'
name: 'Social network icon'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
