enableVersioning: true
handle: card
name: Card
propagationMethod: all
siteSettings:
  6d41e198-048f-42bb-8999-14f1216d94c2:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'card/{slug}'
type: channel
